services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    command: "start --tunnel"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_TUNNEL_URL=https://winning-sheep-only.ngrok-free.app
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/home/node/.n8n:rw
    networks:
      - app_network
  api:
    build:
      context: ./api
    container_name: api
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_network
    # volumes:
    #   - ./api:/src:rw
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: n8n
      MARIADB_USER: n8n
      MARIADB_PASSWORD: n8n
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      timeout: 5s
      retries: 50
    ports:
      - "3303:3306"
    networks:
      - app_network
    volumes:
      - ./mariadb_data:/var/lib/mysql:rw
  # front:
  #   image: php:7.2-apache
  #   container_name: front
  #   ports:
  #     - "8063:80"
  #   volumes:
  #     - ./html:/var/www/html:rw
  #   networks:
  #     - app_network
  #   depends_on:
  #     - api
networks:
  app_network:
    driver: bridge
