services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    command: "start --tunnel"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_TUNNEL_URL=https://winning-sheep-only.ngrok-free.app
    volumes:
      - ./n8n_data:/home/node/.n8n:rw
    networks:
      - app_network
  api:
    build:
      context: ./api
    container_name: api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_network
    # volumes:
    #   - ./api:/src:rw
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: n8n
      MYSQL_USER: n8n
      MYSQL_PASSWORD: n8n
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 50
    ports:
      - "3303:3306"
    networks:
      - app_network
    volumes:
      - ./mysql_data:/var/lib/mysql:rw
  # front:
  #   image: php:7.2-apache
  #   container_name: front
  #   ports:
  #     - "8063:80"
  #   volumes:
  #     - ./html:/var/www/html:rw
  #   networks:
  #     - app_network
  #   depends_on:
  #     - api
networks:
  app_network:
    driver: bridge
